server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
    multipart:
      enabled: true
      max-file-size: 100KB
      max-request-size: 100KB

spring:
  datasource:
    #url: jdbc:sqlserver://14.49.16.134:1433;databaseName=GRMES
    url: jdbc:sqlserver://192.168.0.201:1433;databaseName=FLEXMES_GR
    #url: jdbc:sqlserver://localhost:1433;databaseName=GRMES
    username: sa
    password: georim3005#@!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none #create, update, none
      database: SQL_SERVER
      #defer-datasource-initialization: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   # 테이블 네이밍 전략
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000   #in query의 수(인자를 몇개씩 조회할지에 대한 수)

logging:
  level:
    #ROOT: DEBUG
    org.hibernate.SQL: debug
    #org.hibernate.type: trace

file:
  path: C:\georimtemp\georim\upload\
